### ISSUE TITLE
Incomplete list of extracted commits

### ISSUE THREAD

**Issue by jbon** [jbon/Github-Social-Network-Analysis#1]
The script extracts only the commits of the owners main branch. Other branches and forks are not considered.
See for example the repository: [poppy-humanoid](https://github.com/poppy-project/poppy-humanoid)
Only the commits of the user "poppy-project" are extracted, those of users "humarobotics" and "celiasmith" (smong others) are not extracted.

**Comment by kerstinopen** [comment]
Before a commit is merged, it is not considered as a commit, at least not as one of those that we can extract.

I created a new file with my second account and found out that by creating a new file but not merging it, a new branch is created, but it is not added to the commits,
whereas by sending a pull request and accepting it, the new branch is deleted (because the commit is merged to the master branch), but a new commit is added.

So next, I will try to work around that by not using get_commits(), but get_branches()

**Comment by jbon** [comment]
solved by pull request #9
